/**
 * Created by Mos on 2016/12/12.
 */
export class Organization{
    ORG_CODE:string;
    IS_LEGAL_PERSON:string;
    LEGAL_ORG_CODE:string;
    CONTACT_PERSON:string;
    TEL:string;
    FAX:string;
    MOBILE:string;
    EMAIL:string;
    ADDRESS:string;
    OTHER_CONTACT:string;
    DISTRICT:string;
    COUNTRY:string;
    PROVINCE:string;
    CITY:string;
    STATUS:string;
    CREATEDATE:string;
    CREATOR:string;
    MODIDATE:string;
    MODIBY:string;
    AUDITDATE:string;
    AUDITOR:string;
    COMPANY:string;
    TENANTGROUP:string;
    DATA_SOURCE:string;
    FLAG:number;
    REMARK:string;
    LONGITUDE:string;
    LATITUDE:string;
    SALE_PRICE_REFERENCE_TABLE_NO:string;
    CANDIDATE_SUPPLIER:string;
}